debug: true
logging.level:
    com.alibaba.webplus.demo: DEBUG

site.id: hzpiq39mwz@43a32c297a28a57

quickstart:
  doc.url: https://help.aliyun.com/document_detail/118222.html
  repo:
    name: alibabacloud-webplus-demo-java
    url: https://github.com/aliyun/alibabacloud-webplus-demo-java

app.url: https://webplus.console.aliyun.com/cn-shenzhen/app/app001/env
env.url: https://webplus.console.aliyun.com/cn-shenzhen/app/app001/env/env001/overview

next.step:
  show: false
  package.url: https://webplus-prod-cn-shenzhen.oss-cn-shenzhen.aliyuncs.com/quickstart/java/next-step/webplus-demo-java-0.1.0-SNAPSHOT-exec.jar

news.repository.url: https://webplus-prod-cn-shenzhen.oss-cn-shenzhen.aliyuncs.com/whats-new/
webplus.console.url: https://webplus.console.aliyun.com

spring.thymeleaf.content-type: text/html
spring.thymeleaf.cache: false
spring.thymeleaf.mode: LEGACYHTML5
